name: Fullstack compose deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker frontend image
        run: cd frontend && docker build -t ${{secrets.DOCKER_USERNAME}}/frontend  -f frontend.dockerfile.
      - name: Publish frontend image to docker hub and push
        run: docker push ${{secrets.DOCKER_USERNAME}}/frontend:latest

      - name: Build docker backend image
        run: cd backend && docker build -t ${{secrets.DOCKER_USERNAME}}/backend -f backend.dockerfile .
      - name: Publish backend image to docker hub and push
        run: docker push ${{secrets.DOCKER_USERNAME}}/backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull from docker hub
        run: docker compose pull
      - name: Build and start containers
        run: docker compose up -d --build
